### ISSUE TITLE
Implementation broken when upgrading from 1.1.4 to 1.3.0

### ISSUE THREAD

**Issue by dylanaubrey** [maraisr/meros#24] opened 2023-11-15 14:50 UTC
Hi,

I am currently using 1.1.4 and would like to upgrade to 1.3.0, but the library is not working as expected after the upgrade and I have been unable to isolate the issue through debugging the library... and was hoping you could help.

I am using the browser version of the library like below:

```
import { meros } from 'meros/browser';

const fetchResult = await fetch(url, {
  body: JSON.stringify(body),
  headers: new Headers(this._headers),
  method: 'POST',
}).then(meros);
```

And I am generating the chunked response for my test like below:

```
export const createResponseChunks = (responses: PlainObject[]) => {
  const chunks = responses.map(response => {
    const chunk = Buffer.from(JSON.stringify(response), 'utf8');

    return [
      '',
      '---',
      'Content-Type: application/json; charset=utf-8',
      'Content-Length: ' + String(chunk.length),
      '',
      chunk,
      '',
    ].join('\r\n');
  });

  return `${chunks.join('')}\r\n-----\r\n`;
};
```

This works fine with 1.1.4. From going through your code/commit history I can see you have made some changes to how you deal with `\r\n'`, but I have not been able to refactor the above test code in a way that I can get it working with the library.

Any chance you can guide me as to how I need to format the output of `createResponseChunks` to get it working with the library?

**Comment by maraisr** [comment] 2023-11-23 00:46
Hi @dylanaubrey thank you so much for choosing to upgrade, and your for using my little library! I appreciate you.

About your issue, is it possible the issue is outside of meros? You mentioned that it _used-to_ work in 1.1.4, and not in 1.1.30. Would be nice to see exactly what the payload is that used to work.

I was able to take your code snippet and this worked for me:

```js
import { meros } from './src/browser';

const createResponseChunks = (responses) => {
	const chunks = responses.map((response) => {
		const chunk = Buffer.from(JSON.stringify(response), 'utf8');

		return [
			'',
			'---',
			'Content-Type: application/json; charset=utf-8',
			'Content-Length: ' + String(chunk.length),
			'',
			chunk,
			'',
		].join('\r\n');
	});

	return `${chunks.join('')}\r\n-----\r\n`;
};

const chunks = createResponseChunks(['a', 'b', 'c']);

const response = new Response(chunks, {
	headers: {
		'content-type': 'multipart/mixed;boundary="-"',
	},
});

const parts = await meros(response);

for await (const part of parts) console.log(part);
```

**Comment by maraisr** [comment] 2023-11-26 22:50
Going to close this issue, feel free to comment on here if you're still having issues. I can gladly help!

**Closed by maraisr** 2023-11-26 22:50 UTC
